<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Bugget.BO\Bugget.BO.csproj" />
        <ProjectReference Include="..\Bugget.Entities\Bugget.Entities.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Http" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
      <PackageReference Include="Npgsql" />
    </ItemGroup>
    
</Project>
