<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Bugget.Application\Bugget.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" />
        <PackageReference Include="dbup-postgresql" />
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="Microsoft.Extensions.Logging.Configuration" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
        <PackageReference Include="Npgsql" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Extensions.Logging" />
        <PackageReference Include="Serilog.Settings.Configuration" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Serilog.Sinks.Network" />
        <PackageReference Include="StackExchange.Redis" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="DbUp/sql/migrations/*.sql" />
        <EmbeddedResource Include="DbUp/sql/functions/*.sql" />
        <EmbeddedResource Include="Users/DbUp/sql/*.sql" />
    </ItemGroup>

</Project>
