# Объединённый bugget-api: reports, users и authorization в одном процессе.
upstream app-api {
    zone app-api 64k;
    server app-api:7777 resolve;
}
upstream app-ui {
    zone app-ui 64k;
    server app-ui:80 resolve;
}
