<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Dapper" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bugget.Entities\Bugget.Entities.csproj" />
    <ProjectReference Include="..\Users.Entities\Users.Entities.csproj" />
  </ItemGroup>

</Project>
