<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dbup-postgresql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="sql/migrations/*.sql" />
    <EmbeddedResource Include="sql/functions/*.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bugget.Entities\Bugget.Entities.csproj" />
  </ItemGroup>

</Project>
